---
title: "STA 561 HW4 (SVM & Kernels)"
author: "Daniel Truver"
date: "2/28/2018"
header-includes:
  - \usepackage{ulem}
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### (1) Constructing Kernels 

Let $K_1$ be a kernel.

##### (a) 

$aK_1(x,z)$ is a kernel only if $a > 0$. 

$$
aK_1(x,z) = a\langle \Phi(x), \Phi(z) \rangle = \langle \sqrt{a}\Phi(x), \sqrt{a}\Phi(z) \rangle
$$

##### (b)

The following is not a kernel.

$$
K(x,z) = \langle x,z\rangle ^3 + \left( \langle x,z \rangle - 1 \right)^2 = \langle x,z\rangle ^3 + \langle x,z \rangle^2 - 2\langle x,z \rangle + 1
$$

We can show that it violates the Cauchy-Schwarz Inequality. Take $x = 0$, and $z$ such that $$ ||z||_2^2 \in (0,1).$$

Then 
$$
\begin{aligned}
K(x,z) &= 1 \\
K(x,x) &= 1 \\
K(z,z) &= (||z||_2^2)^3 + (||z||_2^2)^2 - 2||z||_2^2 + 1 \\
&= r < 1 \quad\quad (\text{since }||z||^2 \in (0,1))
\end{aligned}
$$

Now we have 
$$
\sqrt{K(x,x)K(z,z)} = \sqrt{r} < 1 = K(x,z),
$$
which is a violation of the Cauchy-Schwarz Inequality. Therefore, $K$ is not a valid kernel. 

##### (c)

We first note that
$$
k(x,z) = \langle x,z \rangle^2 = \langle x,z \rangle\langle x,z \rangle
$$
is a valid kernel since it is the product of two valid kernels. We know this fact as a result of Mercer's Theorem.
$$
\begin{aligned}
k_1(x,z) &= \sum_{j=1}^\infty \psi_j(x)\psi_j(z) \quad (\text{the }\psi's\text{ have eaten the }\lambda's)\\
k_2(x,z) &= \sum_{i=1}^\infty \Psi_i(x)\Psi_i(z)\\
k_1(x,z)k_2(x,z) &= \sum_{j=1}^\infty\sum_{i=1}^\infty \psi_j(x)\Psi_i(x)\psi_j(z)\Psi_i(z)
\end{aligned}
$$

Take $$\phi_{(i,j)}(x) =  \psi_j(x)\Psi_i(x).$$ We can construct a feature map $\Phi(x)$ with features $\phi_{(i,j)}(x)$.

Then, we have our defined feature map, so 
$$
k_1(x,z)k_2(x,z) = \sum_{(i,j)\in \mathbb{N}\times\mathbb{N}} \phi_{(i,j)}(x) \phi_{(i,j)}(z) = \langle \Phi(x),\Phi(z) \rangle
$$ 
is a kernel. Similarly for the finite case. 

We now play the same game with
$$
\exp(-||x||^2)\exp(-||z||^2).
$$

If we take $g(x) = \exp(-||x||^2)$, then the above is the product $g(x)g(z)$ which is a kernel with feature map $\Phi = g$. 

So, 
$$
K(x,z) = \langle x,z \rangle^2 + \exp(-||x||^2)\exp(-||z||^2)
$$
is a valid kernel 


#### (2) RKHS

We first note that $X = [0,1] \subset \mathbb{R}$ is compact because it is closed and bounded. We next need to show that $\mathcal{F}$ is a Hilbert space. That is, we need it to be a complete innner product space. We'll go with the standard $L_2$ inner product. To show that it is complete, consider a Cauchy sequence of functions $\{f_n(x)\} = \{a_nx\}$ from this space. 

$$\forall \epsilon > 0, ~ \exists N:\forall m >n \geq N $$
$$
\left(\int_0^1 |f_m(x) - f_n(x)|^2 dx\right)^{1/2} < \frac{\epsilon}{\sqrt 3}
$$
The $\sqrt{3}$ will come up later.

We want to show that $\lim \{f_n\} \in \mathcal{F}$.

$$
\begin{aligned}
\left(\int_0^1 |f_m(x) - f_n(x)|^2 dx\right)^{1/2}
&= \left(\int_0^1 |a_mx - a_nx|^2 dx\right)^{1/2} \\
&= \left(\int_0^1 |a_m - a_n|^2x^2 dx\right)^{1/2} \\
&= \frac{1}{\sqrt 3} |a_m - a_n| < \frac{\epsilon}{\sqrt3} \\
\implies 
|a_m - a_n| &< \epsilon
\end{aligned}
$$

This gives us that $\{a_n\}$ is a Cauchy sequence of real numbers, which we know converges to some $a\in \mathbb{R}$. So we are suspicious that $a_nx \to ax$.

We can verify this. Given $\epsilon > 0, ~\exists N$ s.t. $$\forall n\geq N: |a - a_n| < \epsilon, $$ since we know $a_n$ is Cauchy. Therefore
$$
\begin{aligned}
\left(\int_0^1 |f_n(x) - f(x)|^2 dx\right)^{1/2}
&= \left(\int_0^1 |a_n - a|^2x^2 dx\right)^{1/2} \\
&= \frac{1}{\sqrt3}|a_n - a| < \epsilon,
\end{aligned}
$$
and we can say that $$a_nx \to ax : f_n \to f \in \mathcal F. $$ We conclude that $\mathcal F$ is complete and a bonafide Hilbert space. Now, onward to the reproducing property. 

First, we will show that $\forall f \in \mathcal{F}$, we have
$$
f(\cdot) = \sum_{i=1}^m\alpha_ik(\cdot,x_i) = \sum_{i=1}^m \alpha_i (\cdot x_i)
$$

This seems fairly simple. Take $\alpha_1 = 1, x_i = a \in \mathbb{R}$, and obtain $f(x) = k(x,a) = ax$.

We now need $\langle k(\cdot, x), f \rangle = f(x) ~\forall f\in\mathcal{F}$ Again, this seems alright.
$$
\langle k(\cdot, x), f \rangle = \langle k(\cdot, x), k(\cdot, a) \rangle = k(x,a) = ax = f(x)
$$

#### (3) Convexity and KKT Conditions

##### (a) Lagrangian and Dual Form

We first rewrite the constraints so that that appears as $g_i(w, \eta, \eta^*) < 0$ 

$$
\min_{w,\eta,\eta^*} \frac{1}{2}||w||^2 + C\sum_{i=1}^n(\eta_i + \eta_i^*)
$$
subject to 
$$
\begin{aligned}
y_i - w^Tx_i - \epsilon - \eta_i &\leq 0 \\
w^Tx_i - y_i - \epsilon - \eta_i^* &\leq 0 \\
-\eta_i &\leq 0 \\
-\eta_i^* &\leq 0 \\
i &= 1,\dots,n
\end{aligned}
$$

In total, we have $m = 4n$ constraints of the form $g_j(w,\eta,\eta^*) \leq 0$. We write the lagrangian as 
$$
\begin{aligned}
\mathcal{L}(w,\eta,\eta^*,\alpha) 
&= \frac{1}{2}||w||^2 + C\sum_{i=1}^n(\eta_i + \eta_i^*) + \sum_{j=1}^m\alpha_jg_j(w,\eta,\eta^*) \\
&= \frac{1}{2}||w||^2 + C\sum_{i=1}^n(\eta_i + \eta_i^*) \\
&+ \sum_{i=1}^n \alpha_i [y_i - w^Tx_i - \epsilon - \eta_i] + \alpha_{i+n}[w^Tx_i - y_i - \epsilon - \eta_i^*] + \alpha_{i+2n}[-\eta_i] +\alpha_{i+3n}[-\eta_i^*]
\end{aligned}
$$

We now have this painful Lagrangian from which to derive the dual form. Let's begin with the implications of Lagrangian stationarity. 
$$
\begin{aligned}
\nabla_w \mathcal{L}(w,\eta,\eta^*,\alpha) 
&= 0 \\
w + \sum_{i=1}^n [-\alpha_ix_i + \alpha_{i+n}x_i ] &= 0 \implies w = \sum_{i=1}^n [\alpha_ix_i - \alpha_{i+n}x_i ] \\
\nabla_\eta \mathcal{L}(w,\eta,\eta^*,\alpha) &= 0 \implies C - \alpha_i - \alpha_{i + 2n} =0 \\
\nabla_{\eta^*} \mathcal{L}(w,\eta,\eta^*,\alpha) &= 0 \implies C - \alpha_{i+n} - \alpha_{i + 3n} = 0
\end{aligned}
$$
From the other KKT conditions, we get 
$$
\alpha_j \geq 0 ~\forall j \\
\alpha_jg_j(w,\eta,\eta^*) =0 ~\forall j \\
g_j(w, \eta, \eta^*) \leq 0
$$

Now let's expand that Lagrangian and hope for the best. 
$$
\begin{aligned}
\mathcal{L}(w,\eta, \eta^*, \alpha)
&= \frac{1}{2}||w||^2 + C\sum_{i=1}^n(\eta_i + \eta_i^*) \\
&+ \sum_{i=1}^n \alpha_i [y_i - w^Tx_i - \epsilon - \eta_i] + \alpha_{i+n}[w^Tx_i - y_i - \epsilon - \eta_i^*] + \alpha_{i+2n}[-\eta_i] +\alpha_{i+3n}[-\eta_i^*] \\
&= \frac{1}{2}||w||^2 + \sum_{i=1}^nC\eta_i + \sum_{i=1}^nC\eta^* \\
&+ \sum_{i=1}^n \alpha_iy_i - w^T\sum_{i=1}^n\alpha_ix_i - \sum_{i=1}^n\alpha_i\epsilon -\sum_{i=1}^n \alpha_i\eta_i \\
&+ w^T\sum_{i=1}^n \alpha_{i+n}x_i -\sum_{i=1}^n \alpha_{i+n}y_i -\sum_{i=1}^n\alpha_{i+n}\epsilon -\sum_{i=1}^n \alpha_{i+n}\eta^*\\
&- \sum_{i=1}^n\alpha_{i+2n}\eta_i - \sum_{i=1}^n\alpha_{i+3n}\eta_i^* \\
&= \frac{1}{2}||w||^2 + \sout{\sum_{i=1}^n(C - \alpha_i - \alpha_{i+2n})\eta_i} + \sum_{i=1}^n(C-\alpha_{i+n} - \alpha_{i + 3n})\eta_i^* \\
&+ \sum_{i=1}^n \alpha_iy_i - w^T\sum_{i=1}^n\alpha_ix_i - \sum_{i=1}^n\alpha_i\epsilon  \\
&+ w^T\sum_{i=1}^n \alpha_{i+n}x_i -\sum_{i=1}^n \alpha_{i+n}y_i -\sum_{i=1}^n\alpha_{i+n}\epsilon\\
&= 
\end{aligned}
$$

